name = input("Enter your name: ")
uppercase_name = name.upper()
lowercase_name = name.lower()
print("Uppercase: " + uppercase_name)
print("Lowercase: " + lowercase_name)
print(len("Name length: " + name))